---
- name: Install Filebeat on Web VMs
  hosts: webservers
  become: true
  tasks:

  - name: Download deb file
    command: 'curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb'

  - name: Install deb file
    command: 'dpkg -i filebeat-7.4.0-amd64.deb'

  - name: Copy over config file
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Filebeat Enable
    command: 'filebeat modules enable system'

  - name: Setup

    command: 'filebeat setup'

  - name: start
    command: 'service filebeat start'

  - name: Enable Filebeat on startup
    systemd:
      name: filebeat
      enabled: yes
